### ISSUE TITLE
Why negative grad_input of LF_MMI loss?

### ISSUE THREAD

**Issue by glynpu** [jzlianglu/pykaldi2#10]
Hi, 

Why does grad_input multiply -1 in LF_MMI loss Class? 
`grad_input *= -1.0`
[Code Reference:](https://github.com/jzlianglu/pykaldi2/blob/5e988e5968aa9a5867f8179e6c53ea715ac46bdc/ops/ops.py#L141)

Any explanation for this? 
Thank you

**Comment by jzlianglu** [comment]
Because we want to maximize the MMI objective, instead of to minimize it.
