### ISSUE TITLE
Problems about HCLG.fst needed by "train_transformer_se.py"

### ISSUE THREAD

**Issue by SiyuanWei** [jzlianglu/pykaldi2#20]
Hi, I'm implementing your paper "A TRANSFORMER WITH INTERLEAVED SELF-ATTENTION AND CONVOLUTION FOR HYBRID ACOUSTIC MODELS", and I'v got some questions bothering me.
In kaldi setup, sequence training need to create a phone-level language model and denominator fst, which is called HCP in this blog (https://desh2608.github.io/2019-05-21-chain/). In your code, I find that the script "train_transformer_se.py" needs a direction that contains HCLG.fst.
Is the HCLG.fst needed here is equal to the HCP builded based on a phone-level LM.?

**Comment by jzlianglu** [comment]
Hi, you are talking about LF-MMI training of Kaldi. The SE training script for transformer model is using lattice-based approach. For LF-MMI training, please refer to train_chain.py in the "bin" folder. Please note that, the chain model training script only uses batch size as 1. I will update the recipe to support large batch size in the near future.

**Comment by SiyuanWei** [comment]
Oh, Thanks !!!
