### ISSUE TITLE
incompatible pytorch and torchvision version

### ISSUE THREAD

**Issue by csukuangfj** [jzlianglu/pykaldi2#8]
I am trying to install pykaldi2 from source and encountered the following error.

> ERROR: torchvision 0.3.0 has requirement torch>=1.1.0, but you'll 
have torch 1.0.0 which is incompatible.

I chose 1.0.0 because of the following
https://github.com/jzlianglu/pykaldi2/blob/5e988e5968aa9a5867f8179e6c53ea715ac46bdc/docker/Dockerfile#L3
https://github.com/jzlianglu/pykaldi2/blob/5e988e5968aa9a5867f8179e6c53ea715ac46bdc/docker/Dockerfile#L68

Are there any specific reasons to choose `1.0.0` ?

**Comment by jzlianglu** [comment]
You can upgrade PyTorch to 1.20, which is the version that I'm currently using. PyKaldi2 code should still be able to run, and you only need to set the timeout default in dataloader from 1000 to 0. I will update the codebase, and the docker image soon.
